language: ruby
before_install:
  - nvm install
  - npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  target_branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source
branches:
  except:
    - master
