# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Nick Tomlin: Full Stack Engineer"
subtitle: "Always: JavaScript. Occasionally: poetry"
email: "nick.tomlin+web@gmail.com"
permalink: /:year/:month/:day/:title/
description: "I'm Nick Tomlin, a full stack engineer. I like JavaScript."
url: "http://nick-tomlin.com" # the base hostname & protocol for your site
twitter_username: itsnicktomlin
github_username:  nicktomlin
google_analytics_id: "UA-31147245-1"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge

exclude: ["CNAME", "Rakefile", "README.md", "package.json", "node_modules", "javascript", "vendor"]
keep_files: ["javascript"]
