#!/usr/bin/env node

import path from 'path'
import slugify from '@sindresorhus/slugify'
import fs from 'fs'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function main(title) {
  const date = new Date()
  const dateString = date.toISOString().split('T')[0]

  const starterText = `---
title: "${title}"
date: ${dateString}
---`.trim()

  const fileName = `${slugify(title)}.md`
  const dir = path.join(__dirname, '../src/content/posts')
  fs.mkdirSync(dir, { recursive: true })
  const filePath = path.join(dir, fileName)
  fs.writeFileSync(filePath, starterText)
  console.log(`✅ Wrote '${title}' to ${filePath} ✅`)
}

const title = process.argv.slice(2)
if (!/^\S+$/.test(title)) { 
  console.error(`Invalid title supplied: ${title}`) 
}

main(title.join(' ').trim())
